USE univ_elearning;

-- Seed data for users
INSERT IGNORE INTO users (UserID, Username, Email, Password, UserType, Status, EmailVerifiedAt, CreatedAt) VALUES (1, 'admin', 'admin@univ.edu', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Admin', 'Approved', '2026-04-28 12:37:48', '2026-04-28 12:37:48');
INSERT IGNORE INTO users (UserID, Username, Email, Password, UserType, Status, EmailVerifiedAt, CreatedAt) VALUES (2, 'eric', 'njugunaeric82@gmail.com', '$2y$10$ffp/oZ6Yee3IfNVHdeY2VuD36kHFw.Qwrptmh1BMTLxIwt3b9Kvou', 'Student', 'Approved', '2026-04-28 12:56:22', '2026-04-28 12:56:22');
INSERT IGNORE INTO users (UserID, Username, Email, Password, UserType, Status, EmailVerifiedAt, CreatedAt) VALUES (3, 'sir', 'sir@gmail.com', '$2y$10$ZxS8OrMycMurZlQRYD7jfuJ5nmKDCMZoqatBuo4evOWFv5JY4VTou', 'Instructor', 'Approved', '2026-04-28 18:49:28', '2026-04-28 18:49:28');
INSERT IGNORE INTO users (UserID, Username, Email, Password, UserType, Status, EmailVerifiedAt, CreatedAt) VALUES (4, 'tech_instructor', 'instructor@tech.edu', '$2y$10$pojNfh98u2a6pGr3r4eaGe0jpUhL4kZAs2MyXu0yUnnVo3kZzd4bC', 'Instructor', 'Approved', '2026-04-28 19:00:08', '2026-04-28 19:00:08');
INSERT IGNORE INTO users (UserID, Username, Email, Password, UserType, Status, EmailVerifiedAt, CreatedAt) VALUES (5, 'student', 'student@univ.edu', '$2y$10$QdN9L/MuOHKgS8buYDvzF.Rcr2REYT/2LErzrjgQxE/4xK7myszMq', 'Student', 'Approved', '2026-04-28 19:01:30', '2026-04-28 19:01:30');

-- Seed data for courses
INSERT IGNORE INTO courses (CourseID, CourseName, Description, CreatedAt) VALUES (1, 'Python Mastery', 'Master Python from basics to advanced data science.', '2026-04-28 19:00:08');
INSERT IGNORE INTO courses (CourseID, CourseName, Description, CreatedAt) VALUES (2, 'Modern Web Development', 'Build responsive apps with React and Node.js.', '2026-04-28 19:00:27');
INSERT IGNORE INTO courses (CourseID, CourseName, Description, CreatedAt) VALUES (3, 'Database Pro', 'Deep dive into SQL and NoSQL database design.', '2026-04-28 19:00:53');
INSERT IGNORE INTO courses (CourseID, CourseName, Description, CreatedAt) VALUES (4, 'Algorithms & Data Structures', 'The foundation of computer science and interviews.', '2026-04-28 19:00:53');
INSERT IGNORE INTO courses (CourseID, CourseName, Description, CreatedAt) VALUES (5, 'Cloud Architecture', 'Scaling applications using AWS and Google Cloud.', '2026-04-28 19:00:53');
INSERT IGNORE INTO courses (CourseID, CourseName, Description, CreatedAt) VALUES (6, 'AI & Machine Learning', 'Building intelligent systems with TensorFlow.', '2026-04-28 19:00:53');
INSERT IGNORE INTO courses (CourseID, CourseName, Description, CreatedAt) VALUES (7, 'Cyber Defense', 'Protecting networks and systems from modern threats.', '2026-04-28 19:00:53');
INSERT IGNORE INTO courses (CourseID, CourseName, Description, CreatedAt) VALUES (8, 'Flutter App Development', 'Create cross-platform mobile apps with Dart.', '2026-04-28 19:00:54');
INSERT IGNORE INTO courses (CourseID, CourseName, Description, CreatedAt) VALUES (9, 'DevOps Engineering', 'Automating deployment with Docker and Kubernetes.', '2026-04-28 19:00:54');
INSERT IGNORE INTO courses (CourseID, CourseName, Description, CreatedAt) VALUES (10, 'Digital Design (UI/UX)', 'Creating beautiful and functional user interfaces.', '2026-04-28 19:00:54');
INSERT IGNORE INTO courses (CourseID, CourseName, Description, CreatedAt) VALUES (11, 'Java Enterprise', 'Building robust server-side applications with Spring.', '2026-04-28 19:00:54');
INSERT IGNORE INTO courses (CourseID, CourseName, Description, CreatedAt) VALUES (12, 'Network Security', 'Advanced routing, switching, and firewall config.', '2026-04-28 19:00:54');
INSERT IGNORE INTO courses (CourseID, CourseName, Description, CreatedAt) VALUES (13, 'Blockchain Foundations', 'Understanding decentralization and Smart Contracts.', '2026-04-28 19:00:54');
INSERT IGNORE INTO courses (CourseID, CourseName, Description, CreatedAt) VALUES (14, 'Unity Game Engine', 'Creating 2D and 3D games for PC and Mobile.', '2026-04-28 19:00:54');
INSERT IGNORE INTO courses (CourseID, CourseName, Description, CreatedAt) VALUES (15, 'OS Internals', 'Understanding memory management and kernel design.', '2026-04-28 19:00:54');

-- Seed data for instructor_courses
INSERT IGNORE INTO instructor_courses (InstructorCourseID, InstructorID, CourseID, AssignedAt) VALUES (1, 4, 1, '2026-04-28 19:00:08');
INSERT IGNORE INTO instructor_courses (InstructorCourseID, InstructorID, CourseID, AssignedAt) VALUES (2, 4, 2, '2026-04-28 19:00:27');
INSERT IGNORE INTO instructor_courses (InstructorCourseID, InstructorID, CourseID, AssignedAt) VALUES (3, 4, 3, '2026-04-28 19:00:53');
INSERT IGNORE INTO instructor_courses (InstructorCourseID, InstructorID, CourseID, AssignedAt) VALUES (4, 4, 4, '2026-04-28 19:00:53');
INSERT IGNORE INTO instructor_courses (InstructorCourseID, InstructorID, CourseID, AssignedAt) VALUES (5, 4, 5, '2026-04-28 19:00:53');
INSERT IGNORE INTO instructor_courses (InstructorCourseID, InstructorID, CourseID, AssignedAt) VALUES (6, 4, 6, '2026-04-28 19:00:53');
INSERT IGNORE INTO instructor_courses (InstructorCourseID, InstructorID, CourseID, AssignedAt) VALUES (7, 4, 7, '2026-04-28 19:00:54');
INSERT IGNORE INTO instructor_courses (InstructorCourseID, InstructorID, CourseID, AssignedAt) VALUES (8, 4, 8, '2026-04-28 19:00:54');
INSERT IGNORE INTO instructor_courses (InstructorCourseID, InstructorID, CourseID, AssignedAt) VALUES (9, 4, 9, '2026-04-28 19:00:54');
INSERT IGNORE INTO instructor_courses (InstructorCourseID, InstructorID, CourseID, AssignedAt) VALUES (10, 4, 10, '2026-04-28 19:00:54');
INSERT IGNORE INTO instructor_courses (InstructorCourseID, InstructorID, CourseID, AssignedAt) VALUES (11, 4, 11, '2026-04-28 19:00:54');
INSERT IGNORE INTO instructor_courses (InstructorCourseID, InstructorID, CourseID, AssignedAt) VALUES (12, 4, 12, '2026-04-28 19:00:54');
INSERT IGNORE INTO instructor_courses (InstructorCourseID, InstructorID, CourseID, AssignedAt) VALUES (13, 4, 13, '2026-04-28 19:00:54');
INSERT IGNORE INTO instructor_courses (InstructorCourseID, InstructorID, CourseID, AssignedAt) VALUES (14, 4, 14, '2026-04-28 19:00:54');
INSERT IGNORE INTO instructor_courses (InstructorCourseID, InstructorID, CourseID, AssignedAt) VALUES (15, 4, 15, '2026-04-28 19:00:54');

-- Seed data for course_contents
INSERT IGNORE INTO course_contents (ContentID, CourseID, ContentType, ContentTitle, ContentURL) VALUES (1, 1, 'Video', 'Introduction to Python Mastery', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ');
INSERT IGNORE INTO course_contents (ContentID, CourseID, ContentType, ContentTitle, ContentURL) VALUES (2, 1, 'Text', 'Lesson 1: Foundations', 'Refer to the textbook Chapter 1.');
INSERT IGNORE INTO course_contents (ContentID, CourseID, ContentType, ContentTitle, ContentURL) VALUES (3, 2, 'Video', 'Introduction to Modern Web Development', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ');
INSERT IGNORE INTO course_contents (ContentID, CourseID, ContentType, ContentTitle, ContentURL) VALUES (4, 2, 'Text', 'Lesson 1: Foundations', 'Refer to the textbook Chapter 1.');
INSERT IGNORE INTO course_contents (ContentID, CourseID, ContentType, ContentTitle, ContentURL) VALUES (5, 3, 'Video', 'Introduction to Database Pro', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ');
INSERT IGNORE INTO course_contents (ContentID, CourseID, ContentType, ContentTitle, ContentURL) VALUES (6, 3, 'Text', 'Lesson 1: Foundations', 'Refer to the textbook Chapter 1.');
INSERT IGNORE INTO course_contents (ContentID, CourseID, ContentType, ContentTitle, ContentURL) VALUES (7, 4, 'Video', 'Introduction to Algorithms & Data Structures', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ');
INSERT IGNORE INTO course_contents (ContentID, CourseID, ContentType, ContentTitle, ContentURL) VALUES (8, 4, 'Text', 'Lesson 1: Foundations', 'Refer to the textbook Chapter 1.');
INSERT IGNORE INTO course_contents (ContentID, CourseID, ContentType, ContentTitle, ContentURL) VALUES (9, 5, 'Video', 'Introduction to Cloud Architecture', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ');
INSERT IGNORE INTO course_contents (ContentID, CourseID, ContentType, ContentTitle, ContentURL) VALUES (10, 5, 'Text', 'Lesson 1: Foundations', 'Refer to the textbook Chapter 1.');
INSERT IGNORE INTO course_contents (ContentID, CourseID, ContentType, ContentTitle, ContentURL) VALUES (11, 6, 'Video', 'Introduction to AI & Machine Learning', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ');
INSERT IGNORE INTO course_contents (ContentID, CourseID, ContentType, ContentTitle, ContentURL) VALUES (12, 6, 'Text', 'Lesson 1: Foundations', 'Refer to the textbook Chapter 1.');
INSERT IGNORE INTO course_contents (ContentID, CourseID, ContentType, ContentTitle, ContentURL) VALUES (13, 7, 'Video', 'Introduction to Cyber Defense', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ');
INSERT IGNORE INTO course_contents (ContentID, CourseID, ContentType, ContentTitle, ContentURL) VALUES (14, 7, 'Text', 'Lesson 1: Foundations', 'Refer to the textbook Chapter 1.');
INSERT IGNORE INTO course_contents (ContentID, CourseID, ContentType, ContentTitle, ContentURL) VALUES (15, 8, 'Video', 'Introduction to Flutter App Development', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ');
INSERT IGNORE INTO course_contents (ContentID, CourseID, ContentType, ContentTitle, ContentURL) VALUES (16, 8, 'Text', 'Lesson 1: Foundations', 'Refer to the textbook Chapter 1.');
INSERT IGNORE INTO course_contents (ContentID, CourseID, ContentType, ContentTitle, ContentURL) VALUES (17, 9, 'Video', 'Introduction to DevOps Engineering', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ');
INSERT IGNORE INTO course_contents (ContentID, CourseID, ContentType, ContentTitle, ContentURL) VALUES (18, 9, 'Text', 'Lesson 1: Foundations', 'Refer to the textbook Chapter 1.');
INSERT IGNORE INTO course_contents (ContentID, CourseID, ContentType, ContentTitle, ContentURL) VALUES (19, 10, 'Video', 'Introduction to Digital Design (UI/UX)', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ');
INSERT IGNORE INTO course_contents (ContentID, CourseID, ContentType, ContentTitle, ContentURL) VALUES (20, 10, 'Text', 'Lesson 1: Foundations', 'Refer to the textbook Chapter 1.');
INSERT IGNORE INTO course_contents (ContentID, CourseID, ContentType, ContentTitle, ContentURL) VALUES (21, 11, 'Video', 'Introduction to Java Enterprise', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ');
INSERT IGNORE INTO course_contents (ContentID, CourseID, ContentType, ContentTitle, ContentURL) VALUES (22, 11, 'Text', 'Lesson 1: Foundations', 'Refer to the textbook Chapter 1.');
INSERT IGNORE INTO course_contents (ContentID, CourseID, ContentType, ContentTitle, ContentURL) VALUES (23, 12, 'Video', 'Introduction to Network Security', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ');
INSERT IGNORE INTO course_contents (ContentID, CourseID, ContentType, ContentTitle, ContentURL) VALUES (24, 12, 'Text', 'Lesson 1: Foundations', 'Refer to the textbook Chapter 1.');
INSERT IGNORE INTO course_contents (ContentID, CourseID, ContentType, ContentTitle, ContentURL) VALUES (25, 13, 'Video', 'Introduction to Blockchain Foundations', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ');
INSERT IGNORE INTO course_contents (ContentID, CourseID, ContentType, ContentTitle, ContentURL) VALUES (26, 13, 'Text', 'Lesson 1: Foundations', 'Refer to the textbook Chapter 1.');
INSERT IGNORE INTO course_contents (ContentID, CourseID, ContentType, ContentTitle, ContentURL) VALUES (27, 14, 'Video', 'Introduction to Unity Game Engine', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ');
INSERT IGNORE INTO course_contents (ContentID, CourseID, ContentType, ContentTitle, ContentURL) VALUES (28, 14, 'Text', 'Lesson 1: Foundations', 'Refer to the textbook Chapter 1.');
INSERT IGNORE INTO course_contents (ContentID, CourseID, ContentType, ContentTitle, ContentURL) VALUES (29, 15, 'Video', 'Introduction to OS Internals', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ');
INSERT IGNORE INTO course_contents (ContentID, CourseID, ContentType, ContentTitle, ContentURL) VALUES (30, 15, 'Text', 'Lesson 1: Foundations', 'Refer to the textbook Chapter 1.');

-- Seed data for quizzes
INSERT IGNORE INTO quizzes (QuizID, QuizName, CourseID, Description, TotalMarks) VALUES (1, 'Database Pro Entrance Quiz', 3, 'Test your basic knowledge of Database Pro', 100);
INSERT IGNORE INTO quizzes (QuizID, QuizName, CourseID, Description, TotalMarks) VALUES (2, 'Algorithms & Data Structures Entrance Quiz', 4, 'Test your basic knowledge of Algorithms & Data Structures', 100);
INSERT IGNORE INTO quizzes (QuizID, QuizName, CourseID, Description, TotalMarks) VALUES (3, 'Cloud Architecture Entrance Quiz', 5, 'Test your basic knowledge of Cloud Architecture', 100);
INSERT IGNORE INTO quizzes (QuizID, QuizName, CourseID, Description, TotalMarks) VALUES (4, 'AI & Machine Learning Entrance Quiz', 6, 'Test your basic knowledge of AI & Machine Learning', 100);
INSERT IGNORE INTO quizzes (QuizID, QuizName, CourseID, Description, TotalMarks) VALUES (5, 'Cyber Defense Entrance Quiz', 7, 'Test your basic knowledge of Cyber Defense', 100);
INSERT IGNORE INTO quizzes (QuizID, QuizName, CourseID, Description, TotalMarks) VALUES (6, 'Flutter App Development Entrance Quiz', 8, 'Test your basic knowledge of Flutter App Development', 100);
INSERT IGNORE INTO quizzes (QuizID, QuizName, CourseID, Description, TotalMarks) VALUES (7, 'DevOps Engineering Entrance Quiz', 9, 'Test your basic knowledge of DevOps Engineering', 100);
INSERT IGNORE INTO quizzes (QuizID, QuizName, CourseID, Description, TotalMarks) VALUES (8, 'Digital Design (UI/UX) Entrance Quiz', 10, 'Test your basic knowledge of Digital Design (UI/UX)', 100);
INSERT IGNORE INTO quizzes (QuizID, QuizName, CourseID, Description, TotalMarks) VALUES (9, 'Java Enterprise Entrance Quiz', 11, 'Test your basic knowledge of Java Enterprise', 100);
INSERT IGNORE INTO quizzes (QuizID, QuizName, CourseID, Description, TotalMarks) VALUES (10, 'Network Security Entrance Quiz', 12, 'Test your basic knowledge of Network Security', 100);
INSERT IGNORE INTO quizzes (QuizID, QuizName, CourseID, Description, TotalMarks) VALUES (11, 'Blockchain Foundations Entrance Quiz', 13, 'Test your basic knowledge of Blockchain Foundations', 100);
INSERT IGNORE INTO quizzes (QuizID, QuizName, CourseID, Description, TotalMarks) VALUES (12, 'Unity Game Engine Entrance Quiz', 14, 'Test your basic knowledge of Unity Game Engine', 100);
INSERT IGNORE INTO quizzes (QuizID, QuizName, CourseID, Description, TotalMarks) VALUES (13, 'OS Internals Entrance Quiz', 15, 'Test your basic knowledge of OS Internals', 100);

-- Seed data for questions
INSERT IGNORE INTO questions (QuestionID, QuizID, QuestionText, QuestionType, Marks, CreatedAt) VALUES (1, 1, 'What is the primary focus of Database Pro?', 'Multiple Choice', 50, '2026-04-28 19:00:53');
INSERT IGNORE INTO questions (QuestionID, QuizID, QuestionText, QuestionType, Marks, CreatedAt) VALUES (2, 1, 'Which tool is commonly used in Database Pro?', 'Multiple Choice', 50, '2026-04-28 19:00:53');
INSERT IGNORE INTO questions (QuestionID, QuizID, QuestionText, QuestionType, Marks, CreatedAt) VALUES (3, 2, 'What is the primary focus of Algorithms & Data Structures?', 'Multiple Choice', 50, '2026-04-28 19:00:53');
INSERT IGNORE INTO questions (QuestionID, QuizID, QuestionText, QuestionType, Marks, CreatedAt) VALUES (4, 2, 'Which tool is commonly used in Algorithms & Data Structures?', 'Multiple Choice', 50, '2026-04-28 19:00:53');
INSERT IGNORE INTO questions (QuestionID, QuizID, QuestionText, QuestionType, Marks, CreatedAt) VALUES (5, 3, 'What is the primary focus of Cloud Architecture?', 'Multiple Choice', 50, '2026-04-28 19:00:53');
INSERT IGNORE INTO questions (QuestionID, QuizID, QuestionText, QuestionType, Marks, CreatedAt) VALUES (6, 3, 'Which tool is commonly used in Cloud Architecture?', 'Multiple Choice', 50, '2026-04-28 19:00:53');
INSERT IGNORE INTO questions (QuestionID, QuizID, QuestionText, QuestionType, Marks, CreatedAt) VALUES (7, 4, 'What is the primary focus of AI & Machine Learning?', 'Multiple Choice', 50, '2026-04-28 19:00:53');
INSERT IGNORE INTO questions (QuestionID, QuizID, QuestionText, QuestionType, Marks, CreatedAt) VALUES (8, 4, 'Which tool is commonly used in AI & Machine Learning?', 'Multiple Choice', 50, '2026-04-28 19:00:53');
INSERT IGNORE INTO questions (QuestionID, QuizID, QuestionText, QuestionType, Marks, CreatedAt) VALUES (9, 5, 'What is the primary focus of Cyber Defense?', 'Multiple Choice', 50, '2026-04-28 19:00:54');
INSERT IGNORE INTO questions (QuestionID, QuizID, QuestionText, QuestionType, Marks, CreatedAt) VALUES (10, 5, 'Which tool is commonly used in Cyber Defense?', 'Multiple Choice', 50, '2026-04-28 19:00:54');
INSERT IGNORE INTO questions (QuestionID, QuizID, QuestionText, QuestionType, Marks, CreatedAt) VALUES (11, 6, 'What is the primary focus of Flutter App Development?', 'Multiple Choice', 50, '2026-04-28 19:00:54');
INSERT IGNORE INTO questions (QuestionID, QuizID, QuestionText, QuestionType, Marks, CreatedAt) VALUES (12, 6, 'Which tool is commonly used in Flutter App Development?', 'Multiple Choice', 50, '2026-04-28 19:00:54');
INSERT IGNORE INTO questions (QuestionID, QuizID, QuestionText, QuestionType, Marks, CreatedAt) VALUES (13, 7, 'What is the primary focus of DevOps Engineering?', 'Multiple Choice', 50, '2026-04-28 19:00:54');
INSERT IGNORE INTO questions (QuestionID, QuizID, QuestionText, QuestionType, Marks, CreatedAt) VALUES (14, 7, 'Which tool is commonly used in DevOps Engineering?', 'Multiple Choice', 50, '2026-04-28 19:00:54');
INSERT IGNORE INTO questions (QuestionID, QuizID, QuestionText, QuestionType, Marks, CreatedAt) VALUES (15, 8, 'What is the primary focus of Digital Design (UI/UX)?', 'Multiple Choice', 50, '2026-04-28 19:00:54');
INSERT IGNORE INTO questions (QuestionID, QuizID, QuestionText, QuestionType, Marks, CreatedAt) VALUES (16, 8, 'Which tool is commonly used in Digital Design (UI/UX)?', 'Multiple Choice', 50, '2026-04-28 19:00:54');
INSERT IGNORE INTO questions (QuestionID, QuizID, QuestionText, QuestionType, Marks, CreatedAt) VALUES (17, 9, 'What is the primary focus of Java Enterprise?', 'Multiple Choice', 50, '2026-04-28 19:00:54');
INSERT IGNORE INTO questions (QuestionID, QuizID, QuestionText, QuestionType, Marks, CreatedAt) VALUES (18, 9, 'Which tool is commonly used in Java Enterprise?', 'Multiple Choice', 50, '2026-04-28 19:00:54');
INSERT IGNORE INTO questions (QuestionID, QuizID, QuestionText, QuestionType, Marks, CreatedAt) VALUES (19, 10, 'What is the primary focus of Network Security?', 'Multiple Choice', 50, '2026-04-28 19:00:54');
INSERT IGNORE INTO questions (QuestionID, QuizID, QuestionText, QuestionType, Marks, CreatedAt) VALUES (20, 10, 'Which tool is commonly used in Network Security?', 'Multiple Choice', 50, '2026-04-28 19:00:54');
INSERT IGNORE INTO questions (QuestionID, QuizID, QuestionText, QuestionType, Marks, CreatedAt) VALUES (21, 11, 'What is the primary focus of Blockchain Foundations?', 'Multiple Choice', 50, '2026-04-28 19:00:54');
INSERT IGNORE INTO questions (QuestionID, QuizID, QuestionText, QuestionType, Marks, CreatedAt) VALUES (22, 11, 'Which tool is commonly used in Blockchain Foundations?', 'Multiple Choice', 50, '2026-04-28 19:00:54');
INSERT IGNORE INTO questions (QuestionID, QuizID, QuestionText, QuestionType, Marks, CreatedAt) VALUES (23, 12, 'What is the primary focus of Unity Game Engine?', 'Multiple Choice', 50, '2026-04-28 19:00:54');
INSERT IGNORE INTO questions (QuestionID, QuizID, QuestionText, QuestionType, Marks, CreatedAt) VALUES (24, 12, 'Which tool is commonly used in Unity Game Engine?', 'Multiple Choice', 50, '2026-04-28 19:00:54');
INSERT IGNORE INTO questions (QuestionID, QuizID, QuestionText, QuestionType, Marks, CreatedAt) VALUES (25, 13, 'What is the primary focus of OS Internals?', 'Multiple Choice', 50, '2026-04-28 19:00:54');
INSERT IGNORE INTO questions (QuestionID, QuizID, QuestionText, QuestionType, Marks, CreatedAt) VALUES (26, 13, 'Which tool is commonly used in OS Internals?', 'Multiple Choice', 50, '2026-04-28 19:00:54');

-- Seed data for question_options
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (1, 1, 'Foundations', 1);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (2, 1, 'Intermediate', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (3, 1, 'Advanced', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (4, 2, 'Standard Tool A', 1);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (5, 2, 'Niche Tool B', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (6, 2, 'Legacy Tool C', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (7, 3, 'Foundations', 1);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (8, 3, 'Intermediate', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (9, 3, 'Advanced', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (10, 4, 'Standard Tool A', 1);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (11, 4, 'Niche Tool B', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (12, 4, 'Legacy Tool C', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (13, 5, 'Foundations', 1);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (14, 5, 'Intermediate', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (15, 5, 'Advanced', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (16, 6, 'Standard Tool A', 1);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (17, 6, 'Niche Tool B', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (18, 6, 'Legacy Tool C', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (19, 7, 'Foundations', 1);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (20, 7, 'Intermediate', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (21, 7, 'Advanced', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (22, 8, 'Standard Tool A', 1);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (23, 8, 'Niche Tool B', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (24, 8, 'Legacy Tool C', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (25, 9, 'Foundations', 1);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (26, 9, 'Intermediate', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (27, 9, 'Advanced', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (28, 10, 'Standard Tool A', 1);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (29, 10, 'Niche Tool B', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (30, 10, 'Legacy Tool C', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (31, 11, 'Foundations', 1);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (32, 11, 'Intermediate', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (33, 11, 'Advanced', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (34, 12, 'Standard Tool A', 1);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (35, 12, 'Niche Tool B', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (36, 12, 'Legacy Tool C', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (37, 13, 'Foundations', 1);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (38, 13, 'Intermediate', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (39, 13, 'Advanced', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (40, 14, 'Standard Tool A', 1);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (41, 14, 'Niche Tool B', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (42, 14, 'Legacy Tool C', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (43, 15, 'Foundations', 1);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (44, 15, 'Intermediate', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (45, 15, 'Advanced', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (46, 16, 'Standard Tool A', 1);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (47, 16, 'Niche Tool B', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (48, 16, 'Legacy Tool C', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (49, 17, 'Foundations', 1);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (50, 17, 'Intermediate', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (51, 17, 'Advanced', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (52, 18, 'Standard Tool A', 1);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (53, 18, 'Niche Tool B', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (54, 18, 'Legacy Tool C', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (55, 19, 'Foundations', 1);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (56, 19, 'Intermediate', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (57, 19, 'Advanced', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (58, 20, 'Standard Tool A', 1);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (59, 20, 'Niche Tool B', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (60, 20, 'Legacy Tool C', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (61, 21, 'Foundations', 1);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (62, 21, 'Intermediate', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (63, 21, 'Advanced', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (64, 22, 'Standard Tool A', 1);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (65, 22, 'Niche Tool B', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (66, 22, 'Legacy Tool C', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (67, 23, 'Foundations', 1);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (68, 23, 'Intermediate', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (69, 23, 'Advanced', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (70, 24, 'Standard Tool A', 1);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (71, 24, 'Niche Tool B', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (72, 24, 'Legacy Tool C', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (73, 25, 'Foundations', 1);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (74, 25, 'Intermediate', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (75, 25, 'Advanced', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (76, 26, 'Standard Tool A', 1);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (77, 26, 'Niche Tool B', 0);
INSERT IGNORE INTO question_options (OptionID, QuestionID, OptionText, IsCorrect) VALUES (78, 26, 'Legacy Tool C', 0);

